name: lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: instal deps
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: lint-code
        run: |
          make lint